avaliacoes/b3/case2/models/__init__.py
__all__ = [
    'user',
    'book'
]

avaliacoes/b3/case2/models/book.py
from database import get_connection

class Book:
    def __init__(self, titulo, user_id):
        self.titulo = titulo
        self.user_id = user_id

    def save(self):
        conn = get_connection()
        conn.execute("INSERT INTO books(titulo, user_id) values(?,?)", (self.titulo, self.user_id))
        conn.commit()
        conn.close()
        return True

    @classmethod
    def all(cls):
        conn = get_connection()
        books = conn.execute("SELECT * FROM books").fetchall()
        return books

avaliacoes/b3/case2/models/user.py
from database import get_connection
from flask_login import UserMixin

class User(UserMixin):
    def __init__(self, nome, email):
        self.nome = nome
        self.email = email
        self.id = None

    def save(self):
        conn = get_connection()
        conn.execute("INSERT INTO users(email, nome) values(?,?)", (self.email, self.nome))
        conn.commit()
        conn.close()
        return True

    #buscar usuário 
    @classmethod
    def find(cls, **kwargs):
        conn = get_connection()
        if 'email' in kwargs.keys():
            res = conn.execute("SELECT * from users where email = ?", (kwargs['email'],))
        elif 'id' in kwargs.keys():
            res = conn.execute("SELECT * from users where id = ?", (kwargs['id'],))
        else:
            raise AttributeError('A busca deve ser feita por email ou id.')
        data = res.fetchone()
        if data:
            user = User(nome=data['nome'], email=data['email'])
            user.id = data['id']
            return user
        return None
    
    @classmethod
    def all(cls):
        conn = get_connection()
        users = conn.execute("SELECT * FROM users").fetchall()
        return users

avaliacoes/b3/case2/app.py
from flask import Flask
from controllers import users, books

# importar o bluprint e o login manager (PROVA)
from auth.bp import auth_bp, login_manager

app = Flask(__name__)

# configurar secret key (PROVA)
app.config['SECRET_KEY'] = 'ALOHA'

# inicializar o app no login manager (PROVA)
login_manager.init_app(app)

# registrando o blueprint (PROVA)
app.register_blueprint(auth_bp)

app.register_blueprint(users.bp)
app.register_blueprint(books.bp)

@app.route('/')
def index():
    return "<h1>Teste</h1>"

avaliacoes/b3/case2/controllers/__init__.py
all = [
    'books',
    'users'
]

avaliacoes/b3/case2/controllers/books.py
from flask import Flask, render_template, url_for, request, Blueprint, redirect
from flask_login import login_required
from models.user import User
from models.book import Book

bp = Blueprint('books', __name__, url_prefix='/books')

@bp.route('/')
@login_required
def index():
    return render_template('books/index.html', books = Book.all())

@bp.route('/register', methods=['POST', 'GET'])
@login_required
def register():
    
    if request.method == 'POST':
        titulo = request.form['titulo']
        user = request.form['user']

        book = Book(titulo, user)
        book.save()
        return redirect(url_for('books.index'))

    return render_template('books/register.html', users=User.all())

avaliacoes/b3/case2/controllers/users.py
from flask import render_template, Blueprint, url_for, request, flash, redirect
from models.user import User
from flask_login import login_required

bp = Blueprint('users', __name__, url_prefix='/users')

@bp.route('/') 
@login_required
def index():
    return render_template('users/index.html', users = User.all())

@bp.route('/register', methods=['POST', 'GET'])
def register():
    if request.method == 'POST':
        email = request.form['email']
        nome= request.form['nome']

        if not email:
            flash('Email é obrigatório')
        else:
            user = User(nome=nome, email=email)
            user.save()
            #alterar para redirecionar para o blueprint de login
            return redirect(url_for('users.index'))
    
    return render_template('users/register.html')

avaliacoes/b3/case2/database/__init__.py
import sqlite3
import os

DATABASE = 'database.db'
dirname = os.path.dirname(os.path.realpath(__file__))

def get_connection():    
    conn = sqlite3.connect(os.path.join(dirname, DATABASE))
    conn.row_factory = sqlite3.Row
    return conn

avaliacoes/b3/case2/templates/books/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <h1>Lista de Livros</h1>

    <a href="{{url_for('books.register')}}">Adicionar</a>
    <hr>
    {% for book in books %}
    <p>{{book.titulo}}</p>
    {% endfor %}
    
</body>
</html>

avaliacoes/b3/case2/templates/books/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Books - Register</title>
</head>
<body>

    <h1>Registrar Livros</h1>

    <div>
        <h2>Dados</h2>
        <form action="{{url_for('books.register')}}" method="post">
            <input type="text" name="titulo" placeholder="Título" value="{{request.form['titulo']}}">
            <select name="user">
                {% for user in users %}
                    <option value="{{user.id}}">{{user.nome}}</option>    
                {% endfor %}                
            </select>
            <button>Enviar</button>
        </form>
    </div>


    
</body>
</html>

avaliacoes/b3/case2/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
</head>
<body>

    <h1>Lista de Usuários</h1>

    <form action="{{url_for('auth.logout')}}" method="POST">
        <button>
            Sair
        </button>
    </form>

    <a href="{{url_for('users.register')}}">Adicionar</a>

    <hr>
    {% for user in users %}
    <p>{{user.nome}}</p>
    {% endfor %}
    
</body>
</html>

avaliacoes/b3/case2/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <h1>Registro de Usuários</h1>
    <div>
        <h2>Dados</h2>
        <form action="{{url_for('users.register')}}" method="post">
            <input type="email" name="email" placeholder="Email" value="{{request.form['email']}}">
            {% with error = get_flashed_messages()  %}
            <span class="warning">{{error[0]}}</span>    
            {% endwith %}    
            <input type="text" name="nome" placeholder="Nome" value="{{request.form['nome']}}">
            <button>Enviar</button>
        </form>
    
    </div>

</body>
</html>

avaliacoes/b3/case2/templates/users/teste.html
{% extends 'layout.html' %}

{% block content %}
    <h1>Oi</h1>
{% endblock %}